"""Troca tabela Aula - Tema/ Criada usuario

Revision ID: 2dd1ccc2fa16
Revises: 
Create Date: 2026-04-05 21:48:47.428846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd1ccc2fa16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Aluno',
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('contato', sa.String(length=20), nullable=False),
    sa.Column('data_matricula', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=1), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('turno', sa.String(length=1), nullable=False),
    sa.Column('certificado', sa.Boolean(), nullable=False),
    sa.Column('outro_curso', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_aluno')
    )
    op.create_table('Tema',
    sa.Column('id_tema', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_tema')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('Presenca',
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_aula', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['Aluno.id_aluno'], ),
    sa.ForeignKeyConstraint(['id_aula'], ['Tema.id_tema'], ),
    sa.PrimaryKeyConstraint('id_aluno', 'id_aula', 'data')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Presenca')
    op.drop_table('usuario')
    op.drop_table('Tema')
    op.drop_table('Aluno')
    # ### end Alembic commands ###
