"""Initial Migration

Revision ID: 490f7dbdc033
Revises: 0851b68d103b
Create Date: 2026-04-04 21:44:18.783259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '490f7dbdc033'
down_revision: Union[str, Sequence[str], None] = '0851b68d103b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Aluno',
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('contato', sa.String(length=20), nullable=False),
    sa.Column('data_matricula', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=1), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('turno', sa.String(length=1), nullable=False),
    sa.Column('certificado', sa.Boolean(), nullable=False),
    sa.Column('outro_curso', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_aluno')
    )
    op.create_table('Aula',
    sa.Column('id_aula', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_aula')
    )
    op.create_table('Presenca',
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_aula', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['Aluno.id_aluno'], ),
    sa.ForeignKeyConstraint(['id_aula'], ['Aula.id_aula'], ),
    sa.PrimaryKeyConstraint('id_aluno', 'id_aula', 'data')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Presenca')
    op.drop_table('Aula')
    op.drop_table('Aluno')
    # ### end Alembic commands ###
